### ISSUE TITLE
Plugin Worked Once Then Stopped Working

### ISSUE THREAD

**Issue by LordBombShell** [SultanaVerena/SWTOR-Extraction-Tools#1]
I have tried removing and re-adding the plugin. I get this error.
![image](https://user-images.githubusercontent.com/69014860/88967916-793c6400-d27c-11ea-8ceb-4255c6243cac.png)

**Comment by LeeThorogood** [comment]
Hi There, to help me troubleshoot this could you tell me the exact version of Blender you are using and if possible the steps that lead up to this problem?

**Comment by LordBombShell** [comment]
I Just realized that this is happening only in a mode other then Object mode. Title is incorrect.
Blender version 2.79 
Date:2017-09-11 
Hash: 5bd8ac9

Step 1: Open Blender as Admin
Step 2: Change Mode to Edit, Sculpt, or any of the Paint Modes
Step 3: File, Import, SW:TOR (.gr2)
Step 4: Select the file (in this case its any of the leg__skirt archetype for the bmn body type, leg_skirt_bmn_archetype or leg_skirtlegs_bmn_archetype).
Step 5: Receive Error.
Its inconsistent if it it just shows the error and imports it, or if it shows the error and doesn't import it.

**Comment by LeeThorogood** [comment]
Hi, Thanks for the additional information.

I'll investigate if there's anything I can do to fix this, in the meantime to work around the issue my advice would be to only import while in object mode.

**Comment by LeeThorogood** [comment]
Hi, I've just pushed out an update that should resolve this issue. :)
